### ISSUE TITLE
cmd下执行闪退详情

### ISSUE THREAD

**Issue by snaildan** [Zy143L/jd_cookie#16]
Active code page: 65001
Ver: 1.2 By: limoe
https://github.com/Zy143L/jd_cookie
Traceback (most recent call last):
  File "main.py", line 120, in <module>
[10940] Failed to execute script main

**Comment by Zy143L** [comment]
下载新版本

**Comment by snaildan** [comment]
C:\Users\User>CK1.3.1.exe
Active code page: 65001
Ver: 1.3.1 By: limoe
https://github.com/Zy143L/jd_cookie
Traceback (most recent call last):
  File "main.py", line 113, in <module
[15528] Failed to execute script main


1.3.1版
还是报这个

**Comment by snaildan** [comment]
> 下载新版本

C:\Users\User>CK1.3.1.exe
Active code page: 65001
Ver: 1.3.1 By: limoe
https://github.com/Zy143L/jd_cookie
Traceback (most recent call last):
File "main.py", line 113, in <module
[15528] Failed to execute script main

1.3.1版
还是报这个

**Comment by Zy143L** [comment]
你是啥系统呢

**Comment by snaildan** [comment]
> 
> 
> 你是啥系统呢

win7 旗舰版

**Comment by Zy143L** [comment]
..要不考虑下win10?

**Comment by snaildan** [comment]
> 
> 
> ..要不考虑下win10?

好的，谢谢啦

**Comment by hejun041** [comment]
你这个还有为合并的代码  怎么就提上来了呢
